# Generated by Django 3.1.3 on 2021-02-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_assigned_to',
            field=models.CharField(default='', max_length=30),
        ),
    ]
