# Generated by Django 3.1.3 on 2021-02-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210225_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_assigned_to',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
