# Generated by Django 3.1.3 on 2021-02-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210225_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_assigned_by',
            field=models.CharField(default='', editable=False, max_length=30),
        ),
    ]
